### ISSUE TITLE
iOSでのフォント表示が変

### ISSUE THREAD

**Issue by howyi** [voileHQ/voile-front-mock#7]

**Comment by 844196** [comment]
![2018-02-10 15 00 28](https://user-images.githubusercontent.com/4990822/36059056-e173d4de-0e72-11e8-905e-ae5534ddb021.png)

iOS固有の問題というより、element-uiはコンポーネント以外のスタイルは提供されない模様。
提供されているコンポーネント以外の要素のタイポグラフィはブラウザのデフォルトCSSに委ねられる。

**Comment by howyi** [comment]
🙏

**Comment by howyi** [comment]
ありがとうございます 🐔 
なるほど、実際起こってる事象としては「そもそもフォントが指定されていない」ということなんですね、、

**Comment by 844196** [comment]
`font-family` とかを仮当てした:

* 306171038ddf7f2829248b844b511b920fcea582
* e680ec25b7f6434389d8a6ea8aedd3e20e15da36

![img_0071](https://user-images.githubusercontent.com/4990822/36293828-9570eb2e-131f-11e8-8287-bcf7c998f7be.PNG)

**Comment by howyi** [comment]
:thankyou: ❗️
